//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventManagementSystem.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EventManagementSystem.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have changed the number of places.Do you want to change the quantity of products?.
        /// </summary>
        internal static string CHANGING_PLACES_WILL_CHANGE_ITEM_QUANTITY {
            get {
                return ResourceManager.GetString("CHANGING_PLACES_WILL_CHANGE_ITEM_QUANTITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to convert this enquiry into an event?.
        /// </summary>
        internal static string MESSAGE_ASK_BEFORE_BOOKING_ENQUIRY {
            get {
                return ResourceManager.GetString("MESSAGE_ASK_BEFORE_BOOKING_ENQUIRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to close?.
        /// </summary>
        internal static string MESSAGE_ASK_BEFORE_CLOSE_APPLICATION {
            get {
                return ResourceManager.GetString("MESSAGE_ASK_BEFORE_CLOSE_APPLICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this item?.
        /// </summary>
        internal static string MESSAGE_ASK_BEFORE_DELETING_ITEM {
            get {
                return ResourceManager.GetString("MESSAGE_ASK_BEFORE_DELETING_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to change default reminders as the date is changed?.
        /// </summary>
        internal static string MESSAGE_CHANGE_REMINDERS_ON_DATE_CHANGED {
            get {
                return ResourceManager.GetString("MESSAGE_CHANGE_REMINDERS_ON_DATE_CHANGED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to remove the non-edited default reminders as the event type is changed?.
        /// </summary>
        internal static string MESSAGE_CHANGE_REMINDERS_ON_TYPE_CHANGED {
            get {
                return ResourceManager.GetString("MESSAGE_CHANGE_REMINDERS_ON_TYPE_CHANGED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document not found!.
        /// </summary>
        internal static string MESSAGE_DOCUMENT_NOT_FOUND {
            get {
                return ResourceManager.GetString("MESSAGE_DOCUMENT_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function Sheet was created.
        /// </summary>
        internal static string MESSAGE_FUNCTION_SHEET_WAS_CREATED {
            get {
                return ResourceManager.GetString("MESSAGE_FUNCTION_SHEET_WAS_CREATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum of Items to be Invoiced is not equal to sum of Items not to be invoiced.Do You want to continue?.
        /// </summary>
        internal static string MESSAGE_INVOICED_ITEMS_SUM_NOT_EQUAL_TO_NON_INVOICED_ITEMS_SUM {
            get {
                return ResourceManager.GetString("MESSAGE_INVOICED_ITEMS_SUM_NOT_EQUAL_TO_NON_INVOICED_ITEMS_SUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login or password incorrect!.
        /// </summary>
        internal static string MESSAGE_LOGIN_FAILED {
            get {
                return ResourceManager.GetString("MESSAGE_LOGIN_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have successfully logged in. Please wait...
        /// </summary>
        internal static string MESSAGE_LOGIN_SUCCESSFULLY {
            get {
                return ResourceManager.GetString("MESSAGE_LOGIN_SUCCESSFULLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A contact was successfully added!.
        /// </summary>
        internal static string MESSAGE_NEW_CONTACT_ADDED {
            get {
                return ResourceManager.GetString("MESSAGE_NEW_CONTACT_ADDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An event was successfully added!.
        /// </summary>
        internal static string MESSAGE_NEW_EVENT_ADDED {
            get {
                return ResourceManager.GetString("MESSAGE_NEW_EVENT_ADDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An event was successfully updated!.
        /// </summary>
        internal static string MESSAGE_NEW_EVENT_UPDATED {
            get {
                return ResourceManager.GetString("MESSAGE_NEW_EVENT_UPDATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Reminder is Available..
        /// </summary>
        internal static string MESSAGE_NO_REMINDER_AVAILABLE {
            get {
                return ResourceManager.GetString("MESSAGE_NO_REMINDER_AVAILABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The room is already booked and don&apos;t support multiple booking..
        /// </summary>
        internal static string MESSAGE_ROOM_IS_BOOKED {
            get {
                return ResourceManager.GetString("MESSAGE_ROOM_IS_BOOKED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The room is already booked, but supports multiple booking. Do you want to book this room anyway?.
        /// </summary>
        internal static string MESSAGE_ROOM_IS_BOOKED_BUT_SOPPORTS_MULTIBOOKING {
            get {
                return ResourceManager.GetString("MESSAGE_ROOM_IS_BOOKED_BUT_SOPPORTS_MULTIBOOKING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Event Type First..
        /// </summary>
        internal static string MESSAGE_SELECT_EVENTTYPE_FIRST {
            get {
                return ResourceManager.GetString("MESSAGE_SELECT_EVENTTYPE_FIRST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings saved successfully!.
        /// </summary>
        internal static string MESSAGE_SETTINGS_SAVED {
            get {
                return ResourceManager.GetString("MESSAGE_SETTINGS_SAVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tee is already booked. Please select another time intervals..
        /// </summary>
        internal static string MESSAGE_TEE_IS_BOOKED {
            get {
                return ResourceManager.GetString("MESSAGE_TEE_IS_BOOKED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M_X_MEMBERSHIP_ALLOWED.
        /// </summary>
        internal static string PERMISSION__MEMBERSHIP_ALLOWED {
            get {
                return ResourceManager.GetString("PERMISSION__MEMBERSHIP_ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C_X_ACCOUNTS_TAB_ALLOWED.
        /// </summary>
        internal static string PERMISSION_ACCOUNTS_TAB_ALLOWED {
            get {
                return ResourceManager.GetString("PERMISSION_ACCOUNTS_TAB_ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C_X_ACTIVITY_TAB_ALLOWED.
        /// </summary>
        internal static string PERMISSION_ACTIVITY_TAB_ALLOWED {
            get {
                return ResourceManager.GetString("PERMISSION_ACTIVITY_TAB_ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRM_X_ADD_ACTIVITY_ALLOWED.
        /// </summary>
        internal static string PERMISSION_ADD_ACTIVITY_ALLOWED {
            get {
                return ResourceManager.GetString("PERMISSION_ADD_ACTIVITY_ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C_X_ADD_CONTACT_ALLOWED.
        /// </summary>
        internal static string PERMISSION_ADD_CONTACT_ALLOWED {
            get {
                return ResourceManager.GetString("PERMISSION_ADD_CONTACT_ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E_X_ADD_EVENT_ALLOWED.
        /// </summary>
        internal static string PERMISSION_ADD_EVENT_ALLOWED {
            get {
                return ResourceManager.GetString("PERMISSION_ADD_EVENT_ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRM_X_ADD_FOLLOWUP_ALLOWED.
        /// </summary>
        internal static string PERMISSION_ADD_FOLLOWUP_ALLOWED {
            get {
                return ResourceManager.GetString("PERMISSION_ADD_FOLLOWUP_ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M_X_ADD_MEMBER_ALLOWED.
        /// </summary>
        internal static string PERMISSION_ADD_MEMBER_ALLOWED {
            get {
                return ResourceManager.GetString("PERMISSION_ADD_MEMBER_ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A_X_ADD_RESOURCE_ALLOWED.
        /// </summary>
        internal static string PERMISSION_ADD_RESOURCE_ALLOWED {
            get {
                return ResourceManager.GetString("PERMISSION_ADD_RESOURCE_ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B_X_BOOKINGS_ALLOWED.
        /// </summary>
        internal static string PERMISSION_BOOKINGS_ALLOWED {
            get {
                return ResourceManager.GetString("PERMISSION_BOOKINGS_ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRM_X_CHANGE_STATUS_ALLOWED.
        /// </summary>
        internal static string PERMISSION_CHANGE_ENQUIRY_STATUS {
            get {
                return ResourceManager.GetString("PERMISSION_CHANGE_ENQUIRY_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A_X_CLUB_SETTINGS_TAB_ALLOWED.
        /// </summary>
        internal static string PERMISSION_CLUB_SETTINGS_TAB_ALLOWED {
            get {
                return ResourceManager.GetString("PERMISSION_CLUB_SETTINGS_TAB_ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C_X_CONTACT_DETAILS_TAB_ALLOWED.
        /// </summary>
        internal static string PERMISSION_CONTACT_DETAILS_TAB_ALLOWED {
            get {
                return ResourceManager.GetString("PERMISSION_CONTACT_DETAILS_TAB_ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C_X_CONTACTS_ALLOWED.
        /// </summary>
        internal static string PERMISSION_CONTACTS_ALLOWED {
            get {
                return ResourceManager.GetString("PERMISSION_CONTACTS_ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C_X_CORRESPONDENCE_TAB_ALLOWED.
        /// </summary>
        internal static string PERMISSION_CORRESPONDENCE_TAB_ALLOWED {
            get {
                return ResourceManager.GetString("PERMISSION_CORRESPONDENCE_TAB_ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRM_X_CRM_ALLOWED.
        /// </summary>
        internal static string PERMISSION_CRM_ALLOWED {
            get {
                return ResourceManager.GetString("PERMISSION_CRM_ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRM_X_DELETE_ACTIVITY_ALLOWED.
        /// </summary>
        internal static string PERMISSION_DELETE_ACTIVITY_ALLOWED {
            get {
                return ResourceManager.GetString("PERMISSION_DELETE_ACTIVITY_ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E_X_DELETE_EVENT_ALLOWED.
        /// </summary>
        internal static string PERMISSION_DELETE_EVENT_ALLOWED {
            get {
                return ResourceManager.GetString("PERMISSION_DELETE_EVENT_ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRM_X_DELETE_FOLLOWUP_ALLOWED.
        /// </summary>
        internal static string PERMISSION_DELETE_FOLLOWUP_ALLOWED {
            get {
                return ResourceManager.GetString("PERMISSION_DELETE_FOLLOWUP_ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRM_X_DELETE_NOTES_ALLOWED.
        /// </summary>
        internal static string PERMISSION_DELETE_NOTES_ALLOWED {
            get {
                return ResourceManager.GetString("PERMISSION_DELETE_NOTES_ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A_X_DELETE_RESOURCE_ALLOWED.
        /// </summary>
        internal static string PERMISSION_DELETE_RESOURCE_ALLOWED {
            get {
                return ResourceManager.GetString("PERMISSION_DELETE_RESOURCE_ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C_X_EDIT_CONTACT_ALLOWED.
        /// </summary>
        internal static string PERMISSION_EDIT_CONTACT_ALLOWED {
            get {
                return ResourceManager.GetString("PERMISSION_EDIT_CONTACT_ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E_X_EDIT_EVENT_ALLOWED.
        /// </summary>
        internal static string PERMISSION_EDIT_EVENT_ALLOWED {
            get {
                return ResourceManager.GetString("PERMISSION_EDIT_EVENT_ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRM_X_EDIT_EVERYONE_ACTIVITY_ALLOWED.
        /// </summary>
        internal static string PERMISSION_EDIT_EVERYONE_ACTIVITY_ALLOWED {
            get {
                return ResourceManager.GetString("PERMISSION_EDIT_EVERYONE_ACTIVITY_ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRM_X_EDIT_EVERYONE_FOLLOWUP_ALLOWED.
        /// </summary>
        internal static string PERMISSION_EDIT_EVERYONE_FOLLOWUP_ALLOWED {
            get {
                return ResourceManager.GetString("PERMISSION_EDIT_EVERYONE_FOLLOWUP_ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRM_X_EDIT_EVERYONE_NOTE_ALLOWED.
        /// </summary>
        internal static string PERMISSION_EDIT_EVERYONE_NOTE_ALLOWED {
            get {
                return ResourceManager.GetString("PERMISSION_EDIT_EVERYONE_NOTE_ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M_X_EDIT_MEMBER_ALLOWED.
        /// </summary>
        internal static string PERMISSION_EDIT_MEMBER_ALLOWED {
            get {
                return ResourceManager.GetString("PERMISSION_EDIT_MEMBER_ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRM_X_EDIT_OWN_ACTIVITY_ALLOWED.
        /// </summary>
        internal static string PERMISSION_EDIT_OWN_ACTIVITY_ALLOWED {
            get {
                return ResourceManager.GetString("PERMISSION_EDIT_OWN_ACTIVITY_ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRM_X_EDIT_OWN_FOLLOWUP_ALLOWED.
        /// </summary>
        internal static string PERMISSION_EDIT_OWN_FOLLOWUP_ALLOWED {
            get {
                return ResourceManager.GetString("PERMISSION_EDIT_OWN_FOLLOWUP_ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRM_X_EDIT_OWN_NOTE_ALLOWED.
        /// </summary>
        internal static string PERMISSION_EDIT_OWN_NOTE_ALLOWED {
            get {
                return ResourceManager.GetString("PERMISSION_EDIT_OWN_NOTE_ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A_X_EDIT_USERPASSWORD_ALLOWED.
        /// </summary>
        internal static string PERMISSION_EDIT_USERPASSWORD_ALLOWED {
            get {
                return ResourceManager.GetString("PERMISSION_EDIT_USERPASSWORD_ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRM_X_EMAIL_ENQUIRY_ALLOWED.
        /// </summary>
        internal static string PERMISSION_EMAIL_ENQUIRY_ALLOWED {
            get {
                return ResourceManager.GetString("PERMISSION_EMAIL_ENQUIRY_ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E_X_EVENTS_ALLOWED.
        /// </summary>
        internal static string PERMISSION_EVENTS_ALLOWED {
            get {
                return ResourceManager.GetString("PERMISSION_EVENTS_ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A_X_EVENTS_TAB_ALLOWED.
        /// </summary>
        internal static string PERMISSION_EVENTS_TAB_ALLOWED {
            get {
                return ResourceManager.GetString("PERMISSION_EVENTS_TAB_ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A_X_MAIN_ALLOWED.
        /// </summary>
        internal static string PERMISSION_MAIN_ALLOWED {
            get {
                return ResourceManager.GetString("PERMISSION_MAIN_ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M_X_MEMBER_DETAILS_TAB_ALLOWED.
        /// </summary>
        internal static string PERMISSION_MEMBER_DETAILS_TAB_ALLOWED {
            get {
                return ResourceManager.GetString("PERMISSION_MEMBER_DETAILS_TAB_ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M_X_MEMBER_UPDATE_DETAILS_TAB_ALLOWED.
        /// </summary>
        internal static string PERMISSION_MEMBER_UPDATE_DETAILS_TAB_ALLOWED {
            get {
                return ResourceManager.GetString("PERMISSION_MEMBER_UPDATE_DETAILS_TAB_ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A_X_MEMBERS_TAB_ALLOWED.
        /// </summary>
        internal static string PERMISSION_MEMBERS_TAB_ALLOWED {
            get {
                return ResourceManager.GetString("PERMISSION_MEMBERS_TAB_ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M_X_ACCOUNT_DETAILS_TAB_ALLOWED.
        /// </summary>
        internal static string PERMISSION_MEMBERSHIP_ACCOUNTS_TAB_ALLOWED {
            get {
                return ResourceManager.GetString("PERMISSION_MEMBERSHIP_ACCOUNTS_TAB_ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M_X_ACTIVITY_DETAILS_TAB_ALLOWED.
        /// </summary>
        internal static string PERMISSION_MEMBERSHIP_ACTIVITY_TAB_ALLOWED {
            get {
                return ResourceManager.GetString("PERMISSION_MEMBERSHIP_ACTIVITY_TAB_ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M_X_CONTACT_DETAILS_TAB_ALLOWED.
        /// </summary>
        internal static string PERMISSION_MEMBERSHIP_CONTACTS_TAB_ALLOWED {
            get {
                return ResourceManager.GetString("PERMISSION_MEMBERSHIP_CONTACTS_TAB_ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M_X_CORRESPONDENCE_DETAILS_TAB_ALLOWED.
        /// </summary>
        internal static string PERMISSION_MEMBERSHIP_CORRESPONDENCE_TAB_ALLOWED {
            get {
                return ResourceManager.GetString("PERMISSION_MEMBERSHIP_CORRESPONDENCE_TAB_ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M_X_EDIT_CONTACT_ALLOWED.
        /// </summary>
        internal static string PERMISSION_MEMBERSHIP_EDIT_CONTACT_ALLOWED {
            get {
                return ResourceManager.GetString("PERMISSION_MEMBERSHIP_EDIT_CONTACT_ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M_X_NOTE_OVERRIDE.
        /// </summary>
        internal static string PERMISSION_MEMBERSHIP_NOTE_OVERRIDE {
            get {
                return ResourceManager.GetString("PERMISSION_MEMBERSHIP_NOTE_OVERRIDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M_X_NOTES_TAB_ALLOWED.
        /// </summary>
        internal static string PERMISSION_MEMBERSHIP_NOTES_TAB_ALLOWED {
            get {
                return ResourceManager.GetString("PERMISSION_MEMBERSHIP_NOTES_TAB_ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A_X_PRODUCTS_TAB_ALLOWED.
        /// </summary>
        internal static string PERMISSION_PRODUCTS_TAB_ALLOWED {
            get {
                return ResourceManager.GetString("PERMISSION_PRODUCTS_TAB_ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R_X_REPORTS_ALLOWED.
        /// </summary>
        internal static string PERMISSION_REPORTS_ALLOWED {
            get {
                return ResourceManager.GetString("PERMISSION_REPORTS_ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A_X_RESOURCES_TAB_ALLOWED.
        /// </summary>
        internal static string PERMISSION_RESOURCES_TAB_ALLOWED {
            get {
                return ResourceManager.GetString("PERMISSION_RESOURCES_TAB_ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRM_X_SEE_ALL_ACTIVITIES_ALLOWED.
        /// </summary>
        internal static string PERMISSION_SEE_ALL_ACTIVITIES_ALLOWED {
            get {
                return ResourceManager.GetString("PERMISSION_SEE_ALL_ACTIVITIES_ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRM_X_SEE_ALL_ENQUIRIES_ALLOWED.
        /// </summary>
        internal static string PERMISSION_SEE_ALL_ENQUIRIES_ALLOWED {
            get {
                return ResourceManager.GetString("PERMISSION_SEE_ALL_ENQUIRIES_ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRM_X_SEE_ALL_FOLLOWUPS_ALLOWED.
        /// </summary>
        internal static string PERMISSION_SEE_ALL_FOLLOWUPS_ALLOWED {
            get {
                return ResourceManager.GetString("PERMISSION_SEE_ALL_FOLLOWUPS_ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E_X_UNDO_COMMIT_CHARGE.
        /// </summary>
        internal static string PERMISSION_UNDO_COMMIT_CHARGE {
            get {
                return ResourceManager.GetString("PERMISSION_UNDO_COMMIT_CHARGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A_X_USERGROUPS_TAB_ALLOWED.
        /// </summary>
        internal static string PERMISSION_USERGROUPS_TAB_ALLOWED {
            get {
                return ResourceManager.GetString("PERMISSION_USERGROUPS_TAB_ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A_X_USERS_TAB_ALLOWED.
        /// </summary>
        internal static string PERMISSION_USERS_TAB_ALLOWED {
            get {
                return ResourceManager.GetString("PERMISSION_USERS_TAB_ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I.
        /// </summary>
        internal static string SHOW_ON_INVOICE_UNCHECKED_TEXT {
            get {
                return ResourceManager.GetString("SHOW_ON_INVOICE_UNCHECKED_TEXT", resourceCulture);
            }
        }
    }
}
