//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventManagementSystem.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SummariseEvents {
            get {
                return ((bool)(this["SummariseEvents"]));
            }
            set {
                this["SummariseEvents"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IncPrimaryContact {
            get {
                return ((bool)(this["IncPrimaryContact"]));
            }
            set {
                this["IncPrimaryContact"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IncAddress {
            get {
                return ((bool)(this["IncAddress"]));
            }
            set {
                this["IncAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IncEmail {
            get {
                return ((bool)(this["IncEmail"]));
            }
            set {
                this["IncEmail"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IncTelNumbers {
            get {
                return ((bool)(this["IncTelNumbers"]));
            }
            set {
                this["IncTelNumbers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IncPastBookings {
            get {
                return ((bool)(this["IncPastBookings"]));
            }
            set {
                this["IncPastBookings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IncFutureBookings {
            get {
                return ((bool)(this["IncFutureBookings"]));
            }
            set {
                this["IncFutureBookings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IncTotalCharged {
            get {
                return ((bool)(this["IncTotalCharged"]));
            }
            set {
                this["IncTotalCharged"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IncEventDate {
            get {
                return ((bool)(this["IncEventDate"]));
            }
            set {
                this["IncEventDate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IncLastVisit {
            get {
                return ((bool)(this["IncLastVisit"]));
            }
            set {
                this["IncLastVisit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("01/24/2015 17:30:00")]
        public global::System.DateTime StartDateOption {
            get {
                return ((global::System.DateTime)(this["StartDateOption"]));
            }
            set {
                this["StartDateOption"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("01/28/2015 17:30:00")]
        public global::System.DateTime EndDateOption {
            get {
                return ((global::System.DateTime)(this["EndDateOption"]));
            }
            set {
                this["EndDateOption"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IncVATOption {
            get {
                return ((bool)(this["IncVATOption"]));
            }
            set {
                this["IncVATOption"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ExVATOption {
            get {
                return ((bool)(this["ExVATOption"]));
            }
            set {
                this["ExVATOption"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DepartmentOption {
            get {
                return ((bool)(this["DepartmentOption"]));
            }
            set {
                this["DepartmentOption"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GroupOption {
            get {
                return ((bool)(this["GroupOption"]));
            }
            set {
                this["GroupOption"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnquiriesOption {
            get {
                return ((bool)(this["EnquiriesOption"]));
            }
            set {
                this["EnquiriesOption"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ProvisionalOption {
            get {
                return ((bool)(this["ProvisionalOption"]));
            }
            set {
                this["ProvisionalOption"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ConfirmedOption {
            get {
                return ((bool)(this["ConfirmedOption"]));
            }
            set {
                this["ConfirmedOption"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InvoicedOption {
            get {
                return ((bool)(this["InvoicedOption"]));
            }
            set {
                this["InvoicedOption"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CancelledOption {
            get {
                return ((bool)(this["CancelledOption"]));
            }
            set {
                this["CancelledOption"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MinimizedOption {
            get {
                return ((bool)(this["MinimizedOption"]));
            }
            set {
                this["MinimizedOption"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IncMonthlyTotalsOption {
            get {
                return ((bool)(this["IncMonthlyTotalsOption"]));
            }
            set {
                this["IncMonthlyTotalsOption"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int GolfTimeInterval {
            get {
                return ((int)(this["GolfTimeInterval"]));
            }
            set {
                this["GolfTimeInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("01/01/2015 17:30:00")]
        public global::System.DateTime StartDateInDepositsRecevedOption {
            get {
                return ((global::System.DateTime)(this["StartDateInDepositsRecevedOption"]));
            }
            set {
                this["StartDateInDepositsRecevedOption"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12/31/2015 17:31:00")]
        public global::System.DateTime EndDateInDepositsRecevedOption {
            get {
                return ((global::System.DateTime)(this["EndDateInDepositsRecevedOption"]));
            }
            set {
                this["EndDateInDepositsRecevedOption"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsReceivedDateChecked {
            get {
                return ((bool)(this["IsReceivedDateChecked"]));
            }
            set {
                this["IsReceivedDateChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ClubInfoImageUrl {
            get {
                return ((string)(this["ClubInfoImageUrl"]));
            }
            set {
                this["ClubInfoImageUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ClubInfoAddress {
            get {
                return ((string)(this["ClubInfoAddress"]));
            }
            set {
                this["ClubInfoAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ClubInfoFooter {
            get {
                return ((string)(this["ClubInfoFooter"]));
            }
            set {
                this["ClubInfoFooter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ClubInfoBankAccount {
            get {
                return ((string)(this["ClubInfoBankAccount"]));
            }
            set {
                this["ClubInfoBankAccount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int NumberOfDaysToForceReminder {
            get {
                return ((int)(this["NumberOfDaysToForceReminder"]));
            }
            set {
                this["NumberOfDaysToForceReminder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SendEmailToAdminAtTheEndOfEachWeek {
            get {
                return ((bool)(this["SendEmailToAdminAtTheEndOfEachWeek"]));
            }
            set {
                this["SendEmailToAdminAtTheEndOfEachWeek"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SendEmailToAdminAtTheEndOfEachDay {
            get {
                return ((bool)(this["SendEmailToAdminAtTheEndOfEachDay"]));
            }
            set {
                this["SendEmailToAdminAtTheEndOfEachDay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SendDailyEmailWithTasks {
            get {
                return ((bool)(this["SendDailyEmailWithTasks"]));
            }
            set {
                this["SendDailyEmailWithTasks"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SendEmailWhenFollowUpBreached {
            get {
                return ((bool)(this["SendEmailWhenFollowUpBreached"]));
            }
            set {
                this["SendEmailWhenFollowUpBreached"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SendEmailWhenEnquiryAssigned {
            get {
                return ((bool)(this["SendEmailWhenEnquiryAssigned"]));
            }
            set {
                this["SendEmailWhenEnquiryAssigned"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00000000-0000-0000-0000-000000000000")]
        public global::System.Guid DefaultUserIDForEnquiries {
            get {
                return ((global::System.Guid)(this["DefaultUserIDForEnquiries"]));
            }
            set {
                this["DefaultUserIDForEnquiries"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime DailyStartTime {
            get {
                return ((global::System.DateTime)(this["DailyStartTime"]));
            }
            set {
                this["DailyStartTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime WeeklyStartTime {
            get {
                return ((global::System.DateTime)(this["WeeklyStartTime"]));
            }
            set {
                this["WeeklyStartTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CRMEmailHeader {
            get {
                return ((string)(this["CRMEmailHeader"]));
            }
            set {
                this["CRMEmailHeader"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CRMEmailFooter {
            get {
                return ((string)(this["CRMEmailFooter"]));
            }
            set {
                this["CRMEmailFooter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CRMEmailHeaderImage {
            get {
                return ((string)(this["CRMEmailHeaderImage"]));
            }
            set {
                this["CRMEmailHeaderImage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CRMEmailFooterImage {
            get {
                return ((string)(this["CRMEmailFooterImage"]));
            }
            set {
                this["CRMEmailFooterImage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CRMEmailTemplateColor {
            get {
                return ((string)(this["CRMEmailTemplateColor"]));
            }
            set {
                this["CRMEmailTemplateColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int StartDateGroupValue {
            get {
                return ((int)(this["StartDateGroupValue"]));
            }
            set {
                this["StartDateGroupValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int EndDateGroupValue {
            get {
                return ((int)(this["EndDateGroupValue"]));
            }
            set {
                this["EndDateGroupValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DaysForward {
            get {
                return ((int)(this["DaysForward"]));
            }
            set {
                this["DaysForward"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DaysBackward {
            get {
                return ((int)(this["DaysBackward"]));
            }
            set {
                this["DaysBackward"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int StartDateGroupValueDepositReceived {
            get {
                return ((int)(this["StartDateGroupValueDepositReceived"]));
            }
            set {
                this["StartDateGroupValueDepositReceived"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int EndDateGroupValueDepositReceived {
            get {
                return ((int)(this["EndDateGroupValueDepositReceived"]));
            }
            set {
                this["EndDateGroupValueDepositReceived"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DaysBackwardDepositReceived {
            get {
                return ((int)(this["DaysBackwardDepositReceived"]));
            }
            set {
                this["DaysBackwardDepositReceived"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DaysForwardDepositReceived {
            get {
                return ((int)(this["DaysForwardDepositReceived"]));
            }
            set {
                this["DaysForwardDepositReceived"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("01/01/2015 17:30:00")]
        public global::System.DateTime StartDateInPaymentOption {
            get {
                return ((global::System.DateTime)(this["StartDateInPaymentOption"]));
            }
            set {
                this["StartDateInPaymentOption"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12/31/2015 17:30:00")]
        public global::System.DateTime EndDateInPaymentOption {
            get {
                return ((global::System.DateTime)(this["EndDateInPaymentOption"]));
            }
            set {
                this["EndDateInPaymentOption"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int EndDateGroupValuePayment {
            get {
                return ((int)(this["EndDateGroupValuePayment"]));
            }
            set {
                this["EndDateGroupValuePayment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int StartDateGroupValuePayment {
            get {
                return ((int)(this["StartDateGroupValuePayment"]));
            }
            set {
                this["StartDateGroupValuePayment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DaysForwardPayment {
            get {
                return ((int)(this["DaysForwardPayment"]));
            }
            set {
                this["DaysForwardPayment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DaysBackwardPayment {
            get {
                return ((int)(this["DaysBackwardPayment"]));
            }
            set {
                this["DaysBackwardPayment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsPaymentReceivedDateChecked {
            get {
                return ((bool)(this["IsPaymentReceivedDateChecked"]));
            }
            set {
                this["IsPaymentReceivedDateChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int StartDateGroupValueForwardSynopsis {
            get {
                return ((int)(this["StartDateGroupValueForwardSynopsis"]));
            }
            set {
                this["StartDateGroupValueForwardSynopsis"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int EndDateGroupValueForwardSynopsis {
            get {
                return ((int)(this["EndDateGroupValueForwardSynopsis"]));
            }
            set {
                this["EndDateGroupValueForwardSynopsis"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DaysBackwardForwardSynopsis {
            get {
                return ((int)(this["DaysBackwardForwardSynopsis"]));
            }
            set {
                this["DaysBackwardForwardSynopsis"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DaysForwardForwardSynopsis {
            get {
                return ((int)(this["DaysForwardForwardSynopsis"]));
            }
            set {
                this["DaysForwardForwardSynopsis"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("01/01/2015 17:30:00")]
        public global::System.DateTime StartDateForwardSynopsis {
            get {
                return ((global::System.DateTime)(this["StartDateForwardSynopsis"]));
            }
            set {
                this["StartDateForwardSynopsis"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12/31/2015 17:30:00")]
        public global::System.DateTime EndDateForwardSynopsis {
            get {
                return ((global::System.DateTime)(this["EndDateForwardSynopsis"]));
            }
            set {
                this["EndDateForwardSynopsis"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("01/01/2015 17:30:00")]
        public global::System.DateTime StartDateRoundAgeAnalysis {
            get {
                return ((global::System.DateTime)(this["StartDateRoundAgeAnalysis"]));
            }
            set {
                this["StartDateRoundAgeAnalysis"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12/31/2015 17:30:00")]
        public global::System.DateTime EndDateRoundAgeAnalysis {
            get {
                return ((global::System.DateTime)(this["EndDateRoundAgeAnalysis"]));
            }
            set {
                this["EndDateRoundAgeAnalysis"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int StartDateGroupValueRoundAgeAnalysis {
            get {
                return ((int)(this["StartDateGroupValueRoundAgeAnalysis"]));
            }
            set {
                this["StartDateGroupValueRoundAgeAnalysis"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int EndDateGroupValueRoundAgeAnalysis {
            get {
                return ((int)(this["EndDateGroupValueRoundAgeAnalysis"]));
            }
            set {
                this["EndDateGroupValueRoundAgeAnalysis"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DaysForwardRoundAgeAnalysis {
            get {
                return ((int)(this["DaysForwardRoundAgeAnalysis"]));
            }
            set {
                this["DaysForwardRoundAgeAnalysis"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DaysBackwardRoundAgeAnalysis {
            get {
                return ((int)(this["DaysBackwardRoundAgeAnalysis"]));
            }
            set {
                this["DaysBackwardRoundAgeAnalysis"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsGolfOnlyRoundAge {
            get {
                return ((bool)(this["IsGolfOnlyRoundAge"]));
            }
            set {
                this["IsGolfOnlyRoundAge"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsCateringOnlyRoundAge {
            get {
                return ((bool)(this["IsCateringOnlyRoundAge"]));
            }
            set {
                this["IsCateringOnlyRoundAge"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsBothGolfAndCateringRoundAge {
            get {
                return ((bool)(this["IsBothGolfAndCateringRoundAge"]));
            }
            set {
                this["IsBothGolfAndCateringRoundAge"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int StartingPluTillProducts {
            get {
                return ((int)(this["StartingPluTillProducts"]));
            }
            set {
                this["StartingPluTillProducts"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IncPlacesOptionCalender {
            get {
                return ((bool)(this["IncPlacesOptionCalender"]));
            }
            set {
                this["IncPlacesOptionCalender"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IncPrimaryContactOptionCalender {
            get {
                return ((bool)(this["IncPrimaryContactOptionCalender"]));
            }
            set {
                this["IncPrimaryContactOptionCalender"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IncStatusOptionCalender {
            get {
                return ((bool)(this["IncStatusOptionCalender"]));
            }
            set {
                this["IncStatusOptionCalender"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IncEmailOptionCalender {
            get {
                return ((bool)(this["IncEmailOptionCalender"]));
            }
            set {
                this["IncEmailOptionCalender"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IncTelNumbersOptionCalender {
            get {
                return ((bool)(this["IncTelNumbersOptionCalender"]));
            }
            set {
                this["IncTelNumbersOptionCalender"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IncChangesOptionCalender {
            get {
                return ((bool)(this["IncChangesOptionCalender"]));
            }
            set {
                this["IncChangesOptionCalender"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IncStartTimeOptionCalender {
            get {
                return ((bool)(this["IncStartTimeOptionCalender"]));
            }
            set {
                this["IncStartTimeOptionCalender"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IncEventDateOptionCalender {
            get {
                return ((bool)(this["IncEventDateOptionCalender"]));
            }
            set {
                this["IncEventDateOptionCalender"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IncOpeningOption {
            get {
                return ((bool)(this["IncOpeningOption"]));
            }
            set {
                this["IncOpeningOption"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IncJoinersOption {
            get {
                return ((bool)(this["IncJoinersOption"]));
            }
            set {
                this["IncJoinersOption"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IncLeaversOption {
            get {
                return ((bool)(this["IncLeaversOption"]));
            }
            set {
                this["IncLeaversOption"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IncTransfersInOption {
            get {
                return ((bool)(this["IncTransfersInOption"]));
            }
            set {
                this["IncTransfersInOption"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IncTransfersOutOption {
            get {
                return ((bool)(this["IncTransfersOutOption"]));
            }
            set {
                this["IncTransfersOutOption"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IncClosingOption {
            get {
                return ((bool)(this["IncClosingOption"]));
            }
            set {
                this["IncClosingOption"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IncDateSale {
            get {
                return ((bool)(this["IncDateSale"]));
            }
            set {
                this["IncDateSale"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IncMembershipNumber {
            get {
                return ((bool)(this["IncMembershipNumber"]));
            }
            set {
                this["IncMembershipNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IncSalesPerson {
            get {
                return ((bool)(this["IncSalesPerson"]));
            }
            set {
                this["IncSalesPerson"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IncCategoryName {
            get {
                return ((bool)(this["IncCategoryName"]));
            }
            set {
                this["IncCategoryName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IncChargeType {
            get {
                return ((bool)(this["IncChargeType"]));
            }
            set {
                this["IncChargeType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IncMethodOfPayment {
            get {
                return ((bool)(this["IncMethodOfPayment"]));
            }
            set {
                this["IncMethodOfPayment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IncStartDate {
            get {
                return ((bool)(this["IncStartDate"]));
            }
            set {
                this["IncStartDate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IncRenewalDate {
            get {
                return ((bool)(this["IncRenewalDate"]));
            }
            set {
                this["IncRenewalDate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IncIstPaymentMonth {
            get {
                return ((bool)(this["IncIstPaymentMonth"]));
            }
            set {
                this["IncIstPaymentMonth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IncIstMonthPayment {
            get {
                return ((bool)(this["IncIstMonthPayment"]));
            }
            set {
                this["IncIstMonthPayment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IncOutGoingMonthPayment {
            get {
                return ((bool)(this["IncOutGoingMonthPayment"]));
            }
            set {
                this["IncOutGoingMonthPayment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IncLastPaymentMonth {
            get {
                return ((bool)(this["IncLastPaymentMonth"]));
            }
            set {
                this["IncLastPaymentMonth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IncContractPeriod {
            get {
                return ((bool)(this["IncContractPeriod"]));
            }
            set {
                this["IncContractPeriod"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IncAnnualFeePaid {
            get {
                return ((bool)(this["IncAnnualFeePaid"]));
            }
            set {
                this["IncAnnualFeePaid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IncJoiningFeePaid {
            get {
                return ((bool)(this["IncJoiningFeePaid"]));
            }
            set {
                this["IncJoiningFeePaid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IncPromoSource {
            get {
                return ((bool)(this["IncPromoSource"]));
            }
            set {
                this["IncPromoSource"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IncResignDate {
            get {
                return ((bool)(this["IncResignDate"]));
            }
            set {
                this["IncResignDate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IncLeavingDate {
            get {
                return ((bool)(this["IncLeavingDate"]));
            }
            set {
                this["IncLeavingDate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IncMembershipNumberLeavers {
            get {
                return ((bool)(this["IncMembershipNumberLeavers"]));
            }
            set {
                this["IncMembershipNumberLeavers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IncMemberNameLeavers {
            get {
                return ((bool)(this["IncMemberNameLeavers"]));
            }
            set {
                this["IncMemberNameLeavers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IncCategoryNameLeavers {
            get {
                return ((bool)(this["IncCategoryNameLeavers"]));
            }
            set {
                this["IncCategoryNameLeavers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IncReason {
            get {
                return ((bool)(this["IncReason"]));
            }
            set {
                this["IncReason"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IncNotes {
            get {
                return ((bool)(this["IncNotes"]));
            }
            set {
                this["IncNotes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IncLinkedMembers {
            get {
                return ((bool)(this["IncLinkedMembers"]));
            }
            set {
                this["IncLinkedMembers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IncMembershipStart {
            get {
                return ((bool)(this["IncMembershipStart"]));
            }
            set {
                this["IncMembershipStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IncMembershipEnd {
            get {
                return ((bool)(this["IncMembershipEnd"]));
            }
            set {
                this["IncMembershipEnd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IncContractPeriodLeavers {
            get {
                return ((bool)(this["IncContractPeriodLeavers"]));
            }
            set {
                this["IncContractPeriodLeavers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IncLastDDMonth {
            get {
                return ((bool)(this["IncLastDDMonth"]));
            }
            set {
                this["IncLastDDMonth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IncMembers {
            get {
                return ((bool)(this["IncMembers"]));
            }
            set {
                this["IncMembers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IncMemberName {
            get {
                return ((bool)(this["IncMemberName"]));
            }
            set {
                this["IncMemberName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime StartDateOptionJoinersLeavers {
            get {
                return ((global::System.DateTime)(this["StartDateOptionJoinersLeavers"]));
            }
            set {
                this["StartDateOptionJoinersLeavers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime EndDateOptionJoinersLeavers {
            get {
                return ((global::System.DateTime)(this["EndDateOptionJoinersLeavers"]));
            }
            set {
                this["EndDateOptionJoinersLeavers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime StartDateOptionJoinersActivity {
            get {
                return ((global::System.DateTime)(this["StartDateOptionJoinersActivity"]));
            }
            set {
                this["StartDateOptionJoinersActivity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime EndDateOptionJoinersActivity {
            get {
                return ((global::System.DateTime)(this["EndDateOptionJoinersActivity"]));
            }
            set {
                this["EndDateOptionJoinersActivity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime StartDateOptionLeavers {
            get {
                return ((global::System.DateTime)(this["StartDateOptionLeavers"]));
            }
            set {
                this["StartDateOptionLeavers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime EndDateOptionLeavers {
            get {
                return ((global::System.DateTime)(this["EndDateOptionLeavers"]));
            }
            set {
                this["EndDateOptionLeavers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime StartDateOptionTransactions {
            get {
                return ((global::System.DateTime)(this["StartDateOptionTransactions"]));
            }
            set {
                this["StartDateOptionTransactions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime EndDateOptionTransactions {
            get {
                return ((global::System.DateTime)(this["EndDateOptionTransactions"]));
            }
            set {
                this["EndDateOptionTransactions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime StartDateOptionProducts {
            get {
                return ((global::System.DateTime)(this["StartDateOptionProducts"]));
            }
            set {
                this["StartDateOptionProducts"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime EndDateOptionProducts {
            get {
                return ((global::System.DateTime)(this["EndDateOptionProducts"]));
            }
            set {
                this["EndDateOptionProducts"] = value;
            }
        }
    }
}
